### ISSUE TITLE
download the ns_2-bbr-master

### ISSUE THREAD

**Issue by orzrunningsnail** [maesoser/ns2_bbr#2]
Excuse me! I want to know if the repository can work well on the ns2?Sorry, but I can't konw how to operate the step3 and step4. Could you make them more detailed？ Thanks for your time!

**Comment by orzrunningsnail** [comment]
Sorry, they should be step2 and step3.

**Comment by maesoser** [comment]
On step 2 you execute `make patch` in order to patch some ns-2 core files. After that, you do `make all` to copy the new bbr code and compile ns-2 again. You can take a look at the [Makefile](https://github.com/maesoser/ns2_bbr/blob/master/Makefile), it is pretty basic.

And yes, it was designed to work on ns2.35 although, as I said on the [Readme](https://github.com/maesoser/ns2_bbr/blob/master/README.md), this is an *unfinished implementation*.
